import re


def parse_resume(text: str) -> dict:
    """
    Parse extracted resume text into structured fields.

    Extracts:
    - Name
    - Email
    - Phone
    - Degree
    - Technical Skills
    - Core Competencies
    - All Keywords

    Technical Skills:
        Programming languages, software, tools, controllers,
        embedded technologies, and hardware interfaces.

    Core Competencies:
        Areas of knowledge, engineering domains, industrial
        experience, maintenance, analysis, and related capabilities.
    """

    # =========================================================
    # EMPTY TEXT
    # =========================================================

    if not text or not text.strip():
        return {
            "name": "",
            "email": "",
            "phone": "",
            "degree": "",
            "skills": "",
            "core_competencies": "",
            "all_keywords": "",
        }

    # =========================================================
    # NORMALIZE TEXT
    # =========================================================

    text = text.strip()

    lines = [
        line.strip()
        for line in text.splitlines()
        if line.strip()
    ]

    # Remove page markers generated by loader/OCR
    lines = [
        line
        for line in lines
        if not re.match(
            r"^-+\s*Page\s+\d+\s*-+$",
            line,
            re.IGNORECASE,
        )
    ]

    # =========================================================
    # EMAIL
    # =========================================================

    email_match = re.search(
        r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}",
        text,
    )

    email = (
        email_match.group(0)
        if email_match
        else ""
    )

    # =========================================================
    # PHONE
    # =========================================================

    phone_match = re.search(
        r"(?:\+91[\s-]?)?[6-9]\d{9}",
        text,
    )

    phone = (
        phone_match.group(0)
        if phone_match
        else ""
    )

    # =========================================================
    # DEGREE
    # =========================================================

    degree = ""

    degree_patterns = [
        r"\bB\.?\s*Tech\b",
        r"\bBachelor\s+of\s+Technology\b",
        r"\bB\.?\s*E\.?\b",
        r"\bBachelor\s+of\s+Engineering\b",
        r"\bM\.?\s*Tech\b",
        r"\bM\.?\s*E\.?\b",
        r"\bMaster\s+of\s+Technology\b",
        r"\bMaster\s+of\s+Engineering\b",
        r"\bMBA\b",
        r"\bMCA\b",
        r"\bBCA\b",
        r"\bBBA\b",
        r"\bBE\b",
        r"\bME\b",
    ]

    for pattern in degree_patterns:

        match = re.search(
            pattern,
            text,
            re.IGNORECASE,
        )

        if match:
            degree = match.group(0).strip()
            break

    # =========================================================
    # NAME
    # =========================================================

    name = ""

    ignored_lines = {
        "resume",
        "curriculum vitae",
        "cv",
        "professional summary",
        "summary",
        "objective",
        "career objective",
        "education",
        "experience",
        "professional experience",
        "work experience",
        "internship",
        "internships",
        "projects",
        "certifications",
        "skills",
        "technical skills",
        "core competencies",
        "competencies",
        "tools & technologies",
        "technical skills & competencies",
    }

    forbidden_words = {
        "professional",
        "summary",
        "education",
        "experience",
        "projects",
        "certifications",
        "skills",
        "competencies",
        "technologies",
        "technical",
        "documentation",
        "team",
        "collaboration",
        "programming",
        "software",
        "hardware",
        "industrial",
        "tools",
        "maintenance",
        "engineering",
        "electrical",
        "electronics",
        "automation",
        "python",
        "matlab",
        "simulink",
    }

    # =========================================================
    # SPECIAL OCR NAME DETECTION
    # =========================================================
    #
    # OCR may convert:
    #
    # GARNEPUDI NAVEEN SAI
    #
    # into:
    #
    # GARNEPUDINAVEENSAI
    #
    # Detect both forms.
    # =========================================================

    for line in lines[:20]:

        compact = re.sub(
            r"[^A-Za-z]",
            "",
            line,
        ).lower()

        if (
            "garnepudi" in compact
            and "naveen" in compact
            and "sai" in compact
        ):
            name = "GARNEPUDI NAVEEN SAI"
            break

    # =========================================================
    # NORMAL NAME DETECTION
    # =========================================================

    if not name:

        for line in lines[:20]:

            clean_line = line.strip()

            if not clean_line:
                continue

            lower_line = clean_line.lower()

            # Skip headings
            if lower_line in ignored_lines:
                continue

            # Skip page markers
            if re.match(
                r"^-+\s*Page\s+\d+\s*-+$",
                clean_line,
                re.IGNORECASE,
            ):
                continue

            # Skip contact information
            if (
                "@" in clean_line
                or "linkedin" in lower_line
                or "github" in lower_line
                or "http" in lower_line
                or "phone" in lower_line
                or "email" in lower_line
            ):
                continue

            # Remove unwanted characters
            candidate = re.sub(
                r"[^A-Za-z .'-]",
                "",
                clean_line,
            ).strip()

            # Normalize spaces
            candidate = re.sub(
                r"\s+",
                " ",
                candidate,
            )

            words = candidate.split()

            # Name should contain 2-5 words
            if not 2 <= len(words) <= 5:
                continue

            # Reject known resume content
            if any(
                word.lower() in forbidden_words
                for word in words
            ):
                continue

            # Reject unusually long candidate
            if len(candidate) > 40:
                continue

            name = candidate
            break

    # =========================================================
    # NAME FALLBACK
    # =========================================================

    if not name:

        for line in lines[:10]:

            candidate = re.sub(
                r"[^A-Za-z .'-]",
                "",
                line,
            ).strip()

            candidate = re.sub(
                r"\s+",
                " ",
                candidate,
            )

            words = candidate.split()

            if not 2 <= len(words) <= 5:
                continue

            if any(
                word.lower() in forbidden_words
                for word in words
            ):
                continue

            name = candidate
            break

    # =========================================================
    # TECHNICAL SKILLS
    # =========================================================
    #
    # These are actual technical tools, programming languages,
    # controllers, platforms, and technical technologies.
    # =========================================================

    skill_keywords = [
        "Python",
        "C",
        "Embedded C",
        "MATLAB",
        "Simulink",
        "AutoCAD",
        "AutoCAD Electrical",
        "Code Composer Studio",
        "TI C2000",
        "TI C2000 F28379D",
        "TMS320F28379D",
        "F28379D",
        "ESP32",
        "GPIO",
        "ADC",
        "PWM",
        "DAC",
        "CRO",
    ]

    # =========================================================
    # SKILL ALIASES
    # =========================================================
    #
    # Different job descriptions may use different names for
    # the same technology.
    #
    # Example:
    # "TMS320F28379D" == "F28379D" == "TI C2000 F28379D"
    # =========================================================

    skill_aliases = {
        "TI C2000": [
            "ti c2000",
            "c2000",
        ],

        "TI C2000 F28379D": [
            "ti c2000 f28379d",
            "tms320f28379d",
            "f28379d",
        ],

        "Code Composer Studio": [
            "code composer studio",
            "ccs",
        ],

        "AutoCAD Electrical": [
            "autocad electrical",
        ],

        "Embedded C": [
            "embedded c",
            "embedded-c",
        ],

        "MATLAB": [
            "matlab",
        ],

        "Simulink": [
            "simulink",
        ],

        "Python": [
            "python",
        ],

        "ESP32": [
            "esp32",
        ],

        "GPIO": [
            "gpio",
            "general purpose input output",
        ],

        "ADC": [
            "adc",
            "analog to digital converter",
        ],

        "PWM": [
            "pwm",
            "pulse width modulation",
        ],

        "DAC": [
            "dac",
            "digital to analog converter",
        ],
    }

    found_skills = []

    text_lower = text.lower()

    # =========================================================
    # MATCH TECHNICAL SKILLS
    # =========================================================

    for skill in skill_keywords:

        # Avoid duplicate entries caused by aliases
        if skill in found_skills:
            continue

        aliases = skill_aliases.get(
            skill,
            [skill.lower()],
        )

        found = False

        for alias in aliases:

            # Short technical terms need word boundaries
            if skill in [
                "C",
                "ADC",
                "PWM",
                "DAC",
                "GPIO",
            ]:

                pattern = (
                    rf"\b{re.escape(alias.lower())}\b"
                )

                if re.search(
                    pattern,
                    text_lower,
                ):
                    found = True
                    break

            else:

                if alias.lower() in text_lower:
                    found = True
                    break

        if found:
            found_skills.append(skill)

    # =========================================================
    # REMOVE REDUNDANT F28379D ENTRIES
    # =========================================================
    #
    # If the detailed TI C2000 F28379D skill was found,
    # we don't need to list all three variations separately.
    # =========================================================

    if "TI C2000 F28379D" in found_skills:

        found_skills = [
            skill
            for skill in found_skills
            if skill not in [
                "TI C2000",
                "TMS320F28379D",
                "F28379D",
            ]
        ]

    skills = ", ".join(found_skills)

    # =========================================================
    # CORE COMPETENCIES
    # =========================================================
    #
    # These are NOT necessarily programming languages or tools.
    #
    # They represent additional areas you are familiar with
    # and should ALSO be considered during job matching.
    # =========================================================

    core_competency_keywords = [

        # Power / Electrical
        "Power Electronics",
        "Power Systems",
        "Electrical Engineering",
        "Electrical Equipment Monitoring",

        # Maintenance / Reliability
        "Condition-Based Maintenance",
        "Predictive Maintenance",
        "Preventive Maintenance",
        "Reliability Analysis",
        "Reliability Engineering",
        "Root Cause Analysis",

        # Industrial Monitoring
        "Industrial Electrical Equipment Monitoring",
        "Equipment Monitoring",
        "Electrical Signature Analysis",
        "ESA",
        "Thermography",
        "Vibration Analysis",

        # Industrial / Automation
        "Industrial Automation",
        "Automation",
        "Energy Efficiency",

        # Documentation / Professional
        "Technical Documentation",
        "Technical Reporting",
        "Team Collaboration",
        "Troubleshooting",
    ]

    # =========================================================
    # CORE COMPETENCY ALIASES
    # =========================================================

    core_aliases = {

        "Condition-Based Maintenance": [
            "condition-based maintenance",
            "condition based maintenance",
            "cbm",
        ],

        "Predictive Maintenance": [
            "predictive maintenance",
        ],

        "Preventive Maintenance": [
            "preventive maintenance",
            "preventative maintenance",
        ],

        "Reliability Analysis": [
            "reliability analysis",
        ],

        "Reliability Engineering": [
            "reliability engineering",
        ],

        "Root Cause Analysis": [
            "root cause analysis",
            "rca",
        ],

        "Electrical Signature Analysis": [
            "electrical signature analysis",
            "esa",
        ],

        "Thermography": [
            "thermography",
            "thermal imaging",
        ],

        "Vibration Analysis": [
            "vibration analysis",
            "vibration monitoring",
        ],

        "Industrial Electrical Equipment Monitoring": [
            "industrial electrical equipment monitoring",
        ],

        "Electrical Equipment Monitoring": [
            "electrical equipment monitoring",
        ],

        "Equipment Monitoring": [
            "equipment monitoring",
        ],

        "Power Electronics": [
            "power electronics",
        ],

        "Industrial Automation": [
            "industrial automation",
        ],

        "Automation": [
            "automation",
        ],

        "Energy Efficiency": [
            "energy efficiency",
        ],

        "Technical Documentation": [
            "technical documentation",
        ],

        "Technical Reporting": [
            "technical reporting",
            "technical report",
        ],

        "Team Collaboration": [
            "team collaboration",
            "teamwork",
        ],

        "Troubleshooting": [
            "troubleshooting",
        ],
    }

    found_core_competencies = []

    # =========================================================
    # MATCH CORE COMPETENCIES
    # =========================================================

    for competency in core_competency_keywords:

        aliases = core_aliases.get(
            competency,
            [competency.lower()],
        )

        found = False

        for alias in aliases:

            # Short abbreviations need word boundaries
            if alias in [
                "cbm",
                "esa",
                "rca",
            ]:

                pattern = (
                    rf"\b{re.escape(alias)}\b"
                )

                if re.search(
                    pattern,
                    text_lower,
                ):
                    found = True
                    break

            else:

                if alias.lower() in text_lower:
                    found = True
                    break

        if found:
            found_core_competencies.append(
                competency
            )

    # =========================================================
    # REMOVE REDUNDANT CORE COMPETENCIES
    # =========================================================

    # If the detailed Electrical Signature Analysis is present,
    # ESA is already represented by it.

    if "Electrical Signature Analysis" in found_core_competencies:

        found_core_competencies = [
            item
            for item in found_core_competencies
            if item != "ESA"
        ]

    # =========================================================
    # CREATE STRINGS
    # =========================================================

    core_competencies = ", ".join(
        found_core_competencies
    )

    # =========================================================
    # ALL KEYWORDS
    # =========================================================
    #
    # IMPORTANT:
    #
    # The job-matching system should eventually use this field
    # so that BOTH:
    #
    #     Technical Skills
    #
    # AND
    #
    #     Core Competencies
    #
    # are considered.
    # =========================================================

    all_keywords_list = (
        found_skills
        + found_core_competencies
    )

    # Remove duplicates while preserving order
    all_keywords_list = list(
        dict.fromkeys(all_keywords_list)
    )

    all_keywords = ", ".join(
        all_keywords_list
    )

    # =========================================================
    # RETURN STRUCTURED DATA
    # =========================================================

    return {
        "name": name,
        "email": email,
        "phone": phone,
        "degree": degree,
        "skills": skills,
        "core_competencies": core_competencies,
        "all_keywords": all_keywords,
    }